version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: kardexcare
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kishore@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      DATABASE_URL: postgresql://postgres:kishore%40123@postgres:5432/kardexcare?schema=public
      JWT_SECRET: your_jwt_secret_key_here
      JWT_EXPIRES_IN: 90d
      JWT_COOKIE_EXPIRES_IN: 90
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
    command: sh -c "npx prisma migrate deploy && npm start"

volumes:
  postgres_data:
